wandb_version: 1

model_id:
  desc: null
  value: weather_GPT4TS__512_720_100
checkpoints:
  desc: null
  value: ./checkpoints/
root_path:
  desc: null
  value: /home/dan/NeurIPS2023-One-Fits-All/dataset/weather/
data_path:
  desc: null
  value: weather.csv
data:
  desc: null
  value: custom
features:
  desc: null
  value: M
freq:
  desc: null
  value: '0'
target:
  desc: null
  value: OT
embed:
  desc: null
  value: timeF
percent:
  desc: null
  value: 100
seq_len:
  desc: null
  value: 512
pred_len:
  desc: null
  value: 720
label_len:
  desc: null
  value: 48
decay_fac:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 512
num_workers:
  desc: null
  value: 10
train_epochs:
  desc: null
  value: 10
lradj:
  desc: null
  value: type3
patience:
  desc: null
  value: 3
gpt_layers:
  desc: null
  value: 6
is_gpt:
  desc: null
  value: 1
e_layers:
  desc: null
  value: 3
d_model:
  desc: null
  value: 768
n_heads:
  desc: null
  value: 4
d_ff:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.3
enc_in:
  desc: null
  value: 7
c_out:
  desc: null
  value: 7
patch_size:
  desc: null
  value: 16
kernel_size:
  desc: null
  value: 25
loss_func:
  desc: null
  value: mse
pretrain:
  desc: null
  value: 1
freeze:
  desc: null
  value: 1
model:
  desc: null
  value: GPT4TS
stride:
  desc: null
  value: 8
max_len:
  desc: null
  value: -1
hid_dim:
  desc: null
  value: 16
tmax:
  desc: null
  value: 10
itr:
  desc: null
  value: 3
cos:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710860753.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.4
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
