wandb_version: 1

model_id:
  desc: null
  value: imp_EPS_scaled_GPT4TS__18_12_100
checkpoints:
  desc: null
  value: ./checkpoints/
root_path:
  desc: null
  value: /home/dan/NeurIPS2023-One-Fits-All/dataset/Data/
data_path:
  desc: null
  value: df_EPS_CHAR.csv
data:
  desc: null
  value: eps
features:
  desc: null
  value: MS
freq:
  desc: null
  value: '0'
target:
  desc: null
  value: value
embed:
  desc: null
  value: timeF
percent:
  desc: null
  value: 100
seq_len:
  desc: null
  value: 18
pred_len:
  desc: null
  value: 12
label_len:
  desc: null
  value: 9
decay_fac:
  desc: null
  value: 0.75
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 2048
num_workers:
  desc: null
  value: 10
train_epochs:
  desc: null
  value: 500
lradj:
  desc: null
  value: type1
patience:
  desc: null
  value: 3
gpt_layers:
  desc: null
  value: 6
is_gpt:
  desc: null
  value: 1
e_layers:
  desc: null
  value: 3
d_model:
  desc: null
  value: 768
n_heads:
  desc: null
  value: 2
d_ff:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.3
enc_in:
  desc: null
  value: 13149
c_out:
  desc: null
  value: 13149
patch_size:
  desc: null
  value: 16
kernel_size:
  desc: null
  value: 25
loss_func:
  desc: null
  value: mse
pretrain:
  desc: null
  value: 1
freeze:
  desc: null
  value: 1
model:
  desc: null
  value: GPT4TS
stride:
  desc: null
  value: 8
max_len:
  desc: null
  value: -1
hid_dim:
  desc: null
  value: 16
tmax:
  desc: null
  value: 10
itr:
  desc: null
  value: 1
cos:
  desc: null
  value: 1
which_firm:
  desc: null
  value: 285
num_variables:
  desc: null
  value: 18
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715283495.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.4
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
